### ISSUE TITLE
"About" Function is broken on windows Version 0.13

### ISSUE THREAD

**Issue by Himan2001** [FeatherCoin/Feathercoin#267]
When try to show "about" the Wallet is crashing with an exception error in Windows x64

**Comment by Bushstar** [comment]
You are correct, thanks for the report, I'm looking into it now and will produce an updated version once I've tracked down the issue.

**Comment by Bushstar** [comment]
The issue was caused by the wrong string being set for copy right, it's due to a find and replace work around to display both Feathercoin and Bitcoin copyrights. The fix was simply the following.

https://github.com/FeatherCoin/Feathercoin/pull/268/commits/7cecab2d1c4aa7d79d21ea161bef47100a04db21

Please download and try the updated 0.13 client from the following page.

https://github.com/FeatherCoin/Feathercoin/releases/tag/v0.13.0.0
