### ISSUE TITLE
Translation Miss in src/qt/locale/bitcoin_ko_KR.ts

### ISSUE THREAD

**Issue by DongwonTTuna** [FeatherCoin/Feathercoin#312]
src/qt/locale/bitcoin_ko_KR.ts

Change All of '비트코인' to '페더코인' Please (Ctrl + H in notepad)
There's so many translation miss. I'm so sad

changing small things will become to Big things
We are supporting you FTC Team!
Let's talk each other. Dev and Community. This Chemistry is really need in CryptoWorld. :)

Is there no T-shirt that marked Feathercoin logo?

**Comment by DongwonTTuna** [comment]
src/qt/locale/bitcoin_ko_KR.ts ..?

Could you please change bitcoin_ko_KR.ts to feathercoin_ko_KR.ts?

Now I'm Fan of Feathercoin so I hope to participate this.

**Comment by Bushstar** [comment]
No need to rename the file to feathercoin, there are lots of file names with bitcoin in but none make a difference when the compiled binary is presented to the user. Changing file names generates more work.

If you go to the file src/qt/locale/bitcoin_ko_KR.ts in GitHub and edit it then when done it should create a pull request that I can confirm and merge. I'd feel somewhat safer if you performed the edit and I only need to then merge it.

There's no Feathercoin merchandise though it is always possible to get bespoke T-shirts made. Maybe this is something that we should look into.

**Comment by DongwonTTuna** [comment]
Thanks. I created it.

**Comment by Bushstar** [comment]
Thanks for taking the time to update it. I hate to be a pain but the soon to be released version of Feathercoin is on the 0.16 branch and will be the one going into release. If you look at the release tab you can see which versions are marked as stable and can assume that the highest version number is the one currently or soon to be release. master branch does not have translations due to the number of conflicts when we pull locale updates from Bitcoin and the fact that we do not expect it to be used in production.

Could you kindly apply the same to the 0.16 version linked below?

https://github.com/FeatherCoin/Feathercoin/blob/0.16/src/qt/locale/bitcoin_ko_KR.ts

For compatibility with the Feathercoin URIs they need to be left like this feathercoin:
